# Generated by Django 5.0.7 on 2024-07-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='automation_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='scraped_articles_24hrs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='website',
            name='source_active',
            field=models.BooleanField(default=False),
        ),
    ]
