# Generated by Django 5.0.7 on 2024-07-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='website',
            name='status',
        ),
        migrations.RemoveField(
            model_name='website',
            name='url',
        ),
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.URLField(unique=True),
        ),
        migrations.DeleteModel(
            name='ScrapingSession',
        ),
    ]
